[client]
pageScript = "app/Home.py"

[server]
port = 8501
headless = true
runOnSave = false
enableXsrfProtection = true

[logger]
level = "info"

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
